### ISSUE TITLE
Set icon from xml

### ISSUE THREAD

**Issue by coolmyll** [steelkiwi/IncrementProductView#1]
When i set a middle icon from xml it looks really small. Is there any preferred size or option to change it?

`view.setParentMiddleIcon(ContextCompat.getDrawable(getActivity(),R.drawable.ic_raspberry));`

**Comment by soulyaroslav** [comment]
@coolmyll Hi! There isn't preferred size, try to change drawable location. For example to drawable-hdpi it depends on screen size

**Comment by coolmyll** [comment]
This doesnt work for xml drawables. I changed each one width and height code to 100 x 100.

**Comment by soulyaroslav** [comment]
@coolmyll i will check it as soon as possible, thanks for your response

**Comment by soulyaroslav** [comment]
@coolmyll Hi, I fixed issue with icon size calculation, now it will calculate depends on view size. So you can try it now and send some feedback.

**Comment by coolmyll** [comment]
Works perfect now with xml drawables!!!
